### PR TITLE
Make an HTTPS request instead of just HTTP

### LINKED ISSUE #1: Live request is not returning nothing
I just cloned the repo, then run:

``` ruby
bundle exec rake test:live
```

Then I see this error:

``` ruby
Failures:

  1) External request queries FactoryGirl contributors on Github
     Failure/Error: response = Net::HTTP.get(uri)
     EOFError:
       end of file reached
     # ./spec/external_request_spec.rb:7:in `block (2 levels) in <top (required)>'
```

From my understanding this is related with the nature of the protocol, we are using Net:HTTP to to an **https** request.

### PR DESCRIPTION
**Pull request by jmmercadom**
Fixes problems I found trying to follow the tutorial. Fixes #1.
- Does an HTTPS request instead of HTTP.
- Extracts all the request logic to a helper **do_request**

### CODE REVIEW

File: spec/external_request_spec.rb [hunk 1]
```diff
@@ -3,9 +3,18 @@
...
+    response = do_request(uri)
 
-    response = Net::HTTP.get(uri)
+    expect(response).to be_an_instance_of(Net::HTTPOK)
+  end
+
+  def do_request(uri)
+    http = Net::HTTP.new(uri.host, uri.port)
+    http.use_ssl = true
+    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
```
Comment (maxlinc) [inline spec/external_request_spec.rb]: This line shouldn't be necessary.  It would be necessary for self-signed certs or less common CAs, but not the CA used by github.

File: spec/external_request_spec.rb [hunk 2]
```diff
@@ -3,9 +3,18 @@
...
     uri = URI('https://api.github.com/repos/thoughtbot/factory_girl/contributors')
+    response = do_request(uri)
 
-    response = Net::HTTP.get(uri)
+    expect(response).to be_an_instance_of(Net::HTTPOK)
+  end
+
+  def do_request(uri)
+    http = Net::HTTP.new(uri.host, uri.port)
+    http.use_ssl = true
```
Comment (maxlinc) [inline spec/external_request_spec.rb]: `http.use_ssl = uri.scheme == 'https'`

That's actually what ruby 2+ does internally.
